enum objEnum {
    MULTI_OBJ_TEXTURES = 0,
    MULTI_OBJ_MODEL,
    MULTI_OBJ_RENDER_PASS,
    MULTI_OBJ_OBJECT_LAYOUT,
    MULTI_OBJ_GRAPHIC_PIPELINES,
    MULTI_OBJ_GRAPHIC_PIPELINE_LAYOUTS,
    MULTI_OBJ_ENTITIES,
    MULTI_OBJ_SCREEN,
    MULTI_OBJ_TEXTURE_OFFSETS,

    MULTI_OBJ_TEXTURE_1 = 0,

    MULTI_OBJ_MODEL_1 = 0,

    MULTI_OBJ_RENDER_PASS_CLEAN = 0,
    MULTI_OBJ_RENDER_PASS_STAY,

    MULTI_OBJ_OBJECT_LAYOUT_OBJECT = 0,
    MULTI_OBJ_OBJECT_LAYOUT_CAMERA,

    MULTI_OBJ_GRAPHIC_PIPELINES_1 = 0,
    MULTI_OBJ_GRAPHIC_PIPELINE_LAYOUT_1 = 0,

    MULTI_OBJ_ENTITIES_1 = 0,

    MULTI_OBJ_SCREEN_1 = 0,
};
