enum recEnum {
    REC_TEXTURES = 0,
    REC_MODEL,
    REC_RENDER_PASS,
    REC_OBJECT_LAYOUT,
    REC_GRAPHIC_PIPELINES,
    REC_GRAPHIC_PIPELINE_LAYOUTS,
    REC_ENTITIES,
    REC_SCREEN,

    REC_TEXTURE_1 = 0,

    REC_MODEL_1 = 0,

    REC_RENDER_PASS_CLEAN = 0,
    REC_RENDER_PASS_STAY,

    REC_OBJECT_LAYOUT_OBJECT = 0,
    REC_OBJECT_LAYOUT_CAMERA,

    REC_GRAPHIC_PIPELINES_1 = 0,

    REC_GRAPHIC_PIPELINE_LAYOUT_1 = 0,

    REC_ENTITIES_1 = 0,

    REC_SCREEN_1 = 0,
};
