enum recEnum {
    SCREEN_TEXTURES = 0,
    SCREEN_MODEL,
    SCREEN_RENDER_PASS,
    SCREEN_OBJECT_LAYOUT,
    SCREEN_GRAPHIC_PIPELINES,
    SCREEN_GRAPHIC_PIPELINE_LAYOUTS,
    SCREEN_ENTITIES,
    SCREEN_SCREEN,
    SCREEN_COMMAND_QUEUE,

    SCREEN_TEXTURE_1 = 0,

    SCREEN_MODEL_1 = 0,

    SCREEN_RENDER_PASS_CLEAN = 0,
    SCREEN_RENDER_PASS_STAY,

    SCREEN_OBJECT_LAYOUT_OBJECT = 0,
    SCREEN_OBJECT_LAYOUT_CAMERA,

    SCREEN_GRAPHIC_PIPELINES_1 = 0,

    SCREEN_GRAPHIC_PIPELINE_LAYOUT_1 = 0,

    SCREEN_ENTITIES_1 = 0,

    SCREEN_SCREEN_1 = 0,

    SCREEN_COMMAND_QUEUE_GRAPHICS = 0,
};
