enum objEnum {
    GLTF_TEXTURES = 0,
    GLTF_MODEL,
    GLTF_RENDER_PASS,
    GLTF_OBJECT_LAYOUT,
    GLTF_GRAPHIC_PIPELINES,
    GLTF_GRAPHIC_PIPELINE_LAYOUTS,
    GLTF_ENTITIES,
    GLTF_SCREEN,

    GLTF_TEXTURE_1 = 0,

    GLTF_MODEL_1 = 0,

    GLTF_RENDER_PASS_CLEAN = 0,
    GLTF_RENDER_PASS_STAY,

    GLTF_OBJECT_LAYOUT_OBJECT = 0,
    GLTF_OBJECT_LAYOUT_CAMERA,

    GLTF_GRAPHIC_PIPELINES_1 = 0,

    GLTF_GRAPHIC_PIPELINE_LAYOUT_1 = 0,

    GLTF_ENTITIES_1 = 0,

    GLTF_SCREEN_1 = 0,
};
