enum objEnum {
    TWO_ANIMS_GLTF_TEXTURES = 0,
    TWO_ANIMS_GLTF_MODEL,
    TWO_ANIMS_GLTF_RENDER_PASS,
    TWO_ANIMS_GLTF_OBJECT_LAYOUT,
    TWO_ANIMS_GLTF_GRAPHIC_PIPELINES,
    TWO_ANIMS_GLTF_GRAPHIC_PIPELINE_LAYOUTS,
    TWO_ANIMS_GLTF_ENTITIES,
    TWO_ANIMS_GLTF_SCREEN,

    TWO_ANIMS_GLTF_TEXTURE_1 = 0,

    TWO_ANIMS_GLTF_MODEL_1 = 0,

    TWO_ANIMS_GLTF_RENDER_PASS_CLEAN = 0,
    TWO_ANIMS_GLTF_RENDER_PASS_STAY,

    TWO_ANIMS_GLTF_OBJECT_LAYOUT_OBJECT = 0,
    TWO_ANIMS_GLTF_OBJECT_LAYOUT_CAMERA,

    TWO_ANIMS_GLTF_GRAPHIC_PIPELINES_1 = 0,

    TWO_ANIMS_GLTF_GRAPHIC_PIPELINE_LAYOUT_1 = 0,

    TWO_ANIMS_GLTF_ENTITIES_1 = 0,
    TWO_ANIMS_GLTF_ENTITIES_2,

    TWO_ANIMS_GLTF_SCREEN_1 = 0,
};
