enum recEnum {
    COMP_TEXTURES = 0,
    COMP_MODEL,
    COMP_RENDER_PASS,
    COMP_OBJECT_LAYOUT,
    COMP_GRAPHIC_PIPELINES,
    COMP_GRAPHIC_PIPELINE_LAYOUTS,
    COMP_ENTITIES,
    COMP_SCREEN,
    COMP_DESCRIPTOR,
    COMP_BUFFER_DATA,

    COMP_TEXTURE_1 = 0,

    COMP_MODEL_1 = 0,

    COMP_RENDER_PASS_CLEAN = 0,
    COMP_RENDER_PASS_STAY,

    COMP_OBJECT_LAYOUT_OBJECT = 0,
    COMP_OBJECT_LAYOUT_CAMERA,
    COMP_OBJECT_LAYOUT_COMPUTE,

    COMP_GRAPHIC_PIPELINES_1 = 0,
    COMP_GRAPHIC_PIPELINE_COMP,
    COMP_GRAPHIC_PIPELINE_PURE,

    COMP_GRAPHIC_PIPELINE_LAYOUT_1 = 0,
    COMP_GRAPHIC_PIPELINE_LAYOUT_COMP,
    COMP_GRAPHIC_PIPELINE_LAYOUT_PURE,

    COMP_ENTITIES_1 = 0,
    COMP_DRAWCALLS_1,

    COMP_SCREEN_1 = 0,
    COMP_SCREEN_2,

    COMP_BUFFER_DATA_MAPPED = 0,
    COMP_BUFFER_DATA_DATA,
};
