enum generalEnum {
    COMP_TEXT_TEXTURES,
    COMP_TEXT_MODEL,
    COMP_TEXT_RENDER_PASS,
    COMP_TEXT_OBJECT_LAYOUT,
    COMP_TEXT_GRAPHIC_PIPELINES,
    COMP_TEXT_PIPELINE_LAYOUTS,
    COMP_TEXT_ENTITIES,
    COMP_TEXT_SCREEN,
    COMP_TEXT_COMMAND_QUEUE,
    COMP_TEXT_DESCRIPTOR_COMP,
    COMP_TEXT_DESCRIPTOR_FRAG,
    COMP_TEXT_WRITE_TEXTURE,

    COMP_TEXT_TEXTURE_1 = 0,

    COMP_TEXT_MODEL_1 = 0,

    COMP_TEXT_RENDER_PASS_CLEAN = 0,
    COMP_TEXT_RENDER_PASS_STAY,

    COMP_TEXT_OBJECT_LAYOUT_OBJECT = 0,
    COMP_TEXT_OBJECT_LAYOUT_CAMERA,
    COMP_TEXT_OBJECT_LAYOUT_COMPUTE,
    COMP_TEXT_OBJECT_LAYOUT_TEXTURE,

    COMP_TEXT_GRAPHIC_PIPELINES_1 = 0,
    COMP_TEXT_COMPUTE_PIPELINE,

    COMP_TEXT_PIPELINE_LAYOUT_GRAPHICS = 0,
    COMP_TEXT_COMPUTE_PIPELINE_LAYOUT,

    COMP_TEXT_ENTITIES_1 = 0,

    COMP_TEXT_SCREEN_1 = 0,

    COMP_TEXT_COMMAND_QUEUE_GRAPHICS = 0,
    COMP_TEXT_COMMAND_QUEUE_COMPUTE,
};
