enum fontEnum {
    FONT_MODEL = 0,
    FONT_RENDER_PASS,
    FONT_OBJECT_LAYOUT,
    FONT_GRAPHIC_PIPELINES,
    FONT_GRAPHIC_PIPELINE_LAYOUTS,
    FONT_ENTITIES,
    FONT_SCREEN,

    FONT_TEXTURE_1 = 0,

    FONT_MODEL_1 = 0,

    FONT_RENDER_PASS_CLEAN = 0,
    FONT_RENDER_PASS_STAY,

    FONT_OBJECT_LAYOUT_OBJECT = 0,
    FONT_OBJECT_LAYOUT_CAMERA,

    FONT_GRAPHIC_PIPELINES_1 = 0,

    FONT_GRAPHIC_PIPELINE_LAYOUT_1 = 0,

    FONT_ENTITIES_1 = 0,

    FONT_SCREEN_1 = 0,
};
